version: '3'
services:
  api:
    image: "webrecorder/behaviors:latest"
    ports:
      - "3030:3030"
    command: "node ./api/run.js"
    build:
      dockerfile: Dockerfile
      context: .

  behaviors:
    image: "webrecorder/behaviors:latest"
    build:
      dockerfile: ./Dockerfile
      context: .