version: '3'
services:
  api:
    image: "webrecorder/behaviors:latest"
    container_name: "wr-behaviors-api"
    ports:
      - "3030:3030"
    network_mode: "host"
    build:
      dockerfile: Dockerfile
      context: .
